### ISSUE TITLE
这是已经封装成模块了么？

### ISSUE THREAD

**Issue by Yunnathai** [cucygh/ddap#1]

**Comment by beupgo** [comment]
是的，可以直接改改用

**Comment by Yunnathai** [comment]
这个如果要改成一个js广告  可以给别人挂网站的  麻烦吗

**Comment by beupgo** [comment]
不麻烦，不过看你的需求，我这个模块是给复杂的场景用的，比如一个广告位同时放置多家联盟广告，每家广告进行动态流量分配，代码监控等，如果场景简单，可以直接通过iframe引入第三方广告即可

**Comment by Yunnathai** [comment]
我现在有一个项目  需要让我做一段js广告代码  类似百度 谷歌 那种 放在别人网站能直接使用的，可是没有做过，现在没有头绪。可以指点下吗。
